application: fiidup-sql
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application

libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"